Repository Soongsil-Cookie-Time/CookieTime, pull requests merged in 2024-11, with the labels that each got.

#4 feat: change app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/image_app_icon.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat

#7 [Feat] 폰트(공용 리소스) 추가 및 BottomNavigationView 추가
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/ssuclass/cookietime/MainActivity.java
  app/src/main/java/com/ssuclass/cookietime/authservice/AuthActivity.java
  app/src/main/java/com/ssuclass/cookietime/authservice/SIgninDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/authservice/SignupDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/badgemanager/BadgeManagerFragment.java
  app/src/main/java/com/ssuclass/cookietime/community/CommunityFragment.java
  app/src/main/java/com/ssuclass/cookietime/communityservice/CommunityActivity.java
  app/src/main/java/com/ssuclass/cookietime/communityservice/CommunityDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/cookiedetailservice/MovieDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/cookiedetailservice/MovieHomeActivity.java
  app/src/main/java/com/ssuclass/cookietime/cookiedetailservice/SurveyCompleteActivity.java
  app/src/main/java/com/ssuclass/cookietime/cookiedetailservice/SurveyJoinActivity.java
  app/src/main/java/com/ssuclass/cookietime/home/HomeFragment.java
  app/src/main/java/com/ssuclass/cookietime/mypage/MyPageFragment.java
  app/src/main/java/com/ssuclass/cookietime/mypageservice/FriendListActivity.java
  app/src/main/java/com/ssuclass/cookietime/mypageservice/MyPageActivity.java
  app/src/main/res/drawable/uil_arrow_left.xml
  app/src/main/res/drawable/uil_bookmark.xml
  app/src/main/res/drawable/uil_comments.xml
  app/src/main/res/drawable/uil_home_alt.xml
  app/src/main/res/drawable/uil_users_alt.xml
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extra_bold.otf
  app/src/main/res/font/pretendard_extra_light.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semi_bold.otf
  app/src/main/res/font/pretendard_thin.otf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/authservice_signin_detail.xml
  app/src/main/res/layout/authsevice_signup_detail.xml
  app/src/main/res/layout/community_item_layout.xml
  app/src/main/res/layout/communityservice_community.xml
  app/src/main/res/layout/communityservice_communitydetail.xml
  app/src/main/res/layout/cookiedetailservice_moviedetail.xml
  app/src/main/res/layout/cookiedetailservice_moviehome.xml
  app/src/main/res/layout/cookiedetailservice_surveycomplete.xml
  app/src/main/res/layout/cookiedetailservice_surveyjoin.xml
  app/src/main/res/layout/fragment_badge_manager.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/mypageservice_friendlist.xml
  app/src/main/res/layout/mypageservice_mypage.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/navigation_style.xml
  app/src/main/res/values/strings.xml
Labels: feat

#10 feat: "커뮤니티" 화면에서 동작하는 RecyclerView 설계
  app/src/main/java/com/ssuclass/cookietime/ui/community/CommunityDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/ui/community/CommunityDetailAdapter.java
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/viewholder_community_detail.xml
Labels: feat

#11 "커뮤니티"에 해당하는 UI / UX 설계 완료 + FirebaseSDK 추가
  .gitignore
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/ui/community/CommunityDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/ui/community/CommunityWriteActivity.java
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: feat

#15 feat: "배지 관리하기" 화면의 기본동작 UI 설계 완료
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/BadgeManagerFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/FragmentBadgeManagerAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/ItemMonthlyBadgesAdapter.java
  app/src/main/res/drawable/badge_image.xml
  app/src/main/res/drawable/cookie_time_icon.xml
  app/src/main/res/layout/fragment_badge_manager.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_badge.xml
  app/src/main/res/layout/item_monthy_badges.xml
Labels: feat

#16 feat: InstagramSharingButton 동작리스너 연결
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/BadgeManagerFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/FragmentBadgeManagerAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/InstagramSharingActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/badgemanager/ItemMonthlyBadgesAdapter.java
  app/src/main/res/drawable/rounded_rectangle_instagram_card.xml
  app/src/main/res/layout/activity_instagram_sharing.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat

#17 [Feat] KOBIS 영화진흥위원회 오픈 API 호출 로직 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/network/MovieAPI.java
  app/src/main/java/com/ssuclass/cookietime/network/response/KMDbResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/KOBISBoxOfficeResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/KOBISSearchResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/service/KMDbService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/KOBISBoxOfficeService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/KOBISSearchService.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/HomeFragment.java
  app/src/main/res/xml/network_security_config.xml
Labels: feat, chore

#19 feat: DB에서 이미지 다운로드 해서 RecyclerView에 표기
  app/build.gradle.kts
  app/src/main/java/com/ssuclass/cookietime/domain/CommunityEntryModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryFragment.java
Labels: feat

#20 feat: 홈 화면 캐러셀 뷰 UI 구현
  .idea/misc.xml
  app/src/main/java/com/ssuclass/cookietime/network/response/KOBISBoxOfficeResponse.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/CarouselAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/HomeFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/OnCookieButtonClickListener.java
  app/src/main/res/drawable/go_to_cookie_detail_button_background.xml
  app/src/main/res/drawable/home_searchview.xml
  app/src/main/res/drawable/searchview_icon.xml
  app/src/main/res/drawable/star_icon.xml
  app/src/main/res/font/baloo_regular.ttf
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_boxoffice.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: feat

#25 feat: 누락된 ViewHolderListener 동작 코드 추가
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryAdapter.java
Labels: feat

#26 feat: 로그인 xml 구현
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/Login.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/MainLogin.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/Signup.java
  app/src/main/res/drawable/button_rounded.xml
  app/src/main/res/drawable/edit_text_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/values/style.xml
Labels: feat

#27 feat: KOBIS 박스오피스 API를 TMDB 현재 상영작 API로 변경
  app/build.gradle.kts
  app/src/main/java/com/ssuclass/cookietime/network/MovieAPI.java
  app/src/main/java/com/ssuclass/cookietime/network/response/KMDbResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/KOBISBoxOfficeResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/KOBISSearchResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/TMDBMovieDetailResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/TMDBMovieSearchResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/response/TMDBNowPlayingResponse.java
  app/src/main/java/com/ssuclass/cookietime/network/service/KMDbService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/KOBISBoxOfficeService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/KOBISSearchService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/TMDBMovieDetailService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/TMDBMovieSearchService.java
  app/src/main/java/com/ssuclass/cookietime/network/service/TMDBNowPlayingService.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/CarouselAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/HomeFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/OnCookieButtonClickListener.java
  app/src/main/res/layout/fragment_home.xml
Labels: feat

#28 feat: 개편된 DB를 기반으로 기존에 CommunityDetailActivity 동작 완료
  app/src/main/java/com/ssuclass/cookietime/domain/CommunityDetailModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityDetailActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityDetailAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryFragment.java
Labels: feat

#29 feat: 쿠키 정보 UI 구현
  app/src/main/java/com/ssuclass/cookietime/domain/CookieKeywordModel.java
  app/src/main/java/com/ssuclass/cookietime/domain/SurveyProgressModel.java
  app/src/main/java/com/ssuclass/cookietime/network/response/TMDBMovieDetailResponse.java
  app/src/main/java/com/ssuclass/cookietime/presentation/MainActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/cookieinfo/CookieInfoFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/cookieinfo/KeywordAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/cookieinfo/SurveyProgressAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/home/HomeFragment.java
  app/src/main/res/drawable/cookie_info_survey_progress_bar.xml
  app/src/main/res/drawable/go_to_cookie_community_button.xml
  app/src/main/res/drawable/survey_keyword_background.xml
  app/src/main/res/layout/fragment_cookie_info.xml
  app/src/main/res/layout/item_cookie_survey_keyword.xml
  app/src/main/res/layout/item_cookie_survey_progress_bar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: feat

#31 feat: 마이페이지 레이아웃 설계 완료
  .idea/misc.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/MyPageFragment.java
  app/src/main/res/drawable/uil_angle_right.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
Labels: feat

#32 fix: fragment_my_page.xml layout 제약조건 수정
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/MyPageFragment.java
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat

#33 feat: MyPageFragment.java에서 로그아웃 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/LoginActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/MainLoginActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/SignupActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/CommunityEntryFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/MyPageFragment.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_login.xml
  app/src/main/res/layout/activity_signup.xml
Labels: feat

#34 feat: 사용자 인증 로직 구현 완료
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/AuthentiacationActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/LoginActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/MainLoginActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/SigninActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/SignupActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/bottomnavigation/MainActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/MyPageFragment.java
  app/src/main/res/layout/activity_authentication.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
Labels: feat

#35 feat: 사용자 정보 DB에 추가
  app/src/main/java/com/ssuclass/cookietime/presentation/Login/SignupActivity.java
  app/src/main/res/layout/activity_signup.xml
Labels: feat

#36 [Feat] Firestore DB와 쿠키 정보 데이터 연동
  app/src/main/java/com/ssuclass/cookietime/domain/CookieKeywordModel.java
  app/src/main/java/com/ssuclass/cookietime/domain/SurveyProgressModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/cookieinfo/CookieInfoFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/cookieinfo/KeywordAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/cookieinfo/SurveyProgressAdapter.java
  app/src/main/res/layout/fragment_cookie_info.xml
Labels: feat

#38 feat: 댓글 화면 구현 및 DB 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/data/CommunityRepository.java
  app/src/main/java/com/ssuclass/cookietime/domain/CommunityDetailModel.java
  app/src/main/java/com/ssuclass/cookietime/domain/community/CommentsModel.java
  app/src/main/java/com/ssuclass/cookietime/domain/community/CommunityModel.java
  app/src/main/java/com/ssuclass/cookietime/domain/community/PostsModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/bottomnavigation/MainActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/detail/PostsActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/detail/PostsAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/entry/CommunitiesAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/entry/CommunitiesFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/post/CommentsActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/post/CommentsAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/write/PostsWriteActivity.java
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/activity_post.xml
  app/src/main/res/layout/item_comment.xml
Labels: feat

#39 feat: 마이페이지 비즈니스 로직 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/authentication/AuthentiacationActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/authentication/SigninActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/authentication/SignupActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/comments/CommentsActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/comments/CommentsAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/comments/CommentsModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/entry/CommunitiesAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/entry/CommunitiesFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/entry/CommunitiesModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/posts/PostsActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/posts/PostsAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/community/posts/PostsModel.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/MyPageFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/change/nickname/ChangeNicknameActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/change/password/ChangePasswordActivity.java
  app/src/main/java/com/ssuclass/cookietime/util/FirebaseConstants.java
  app/src/main/res/layout/activity_authentication.xml
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_post.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat, fix

#40 feat: 친구목록 RecyclerView에 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/MyPageFragment.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/friendlist/FriendListActivity.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/friendlist/FriendListAdapter.java
  app/src/main/java/com/ssuclass/cookietime/presentation/mypage/friendlist/FriendListModel.java
  app/src/main/res/layout/activity_friend_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_friend_info.xml
Labels: feat
